### ISSUE TITLE
Do you have a JavaScript client that can connect to an instance of this running on the server?

### ISSUE THREAD

**Issue by xmuskrat** [permitio/fastapi_websocket_pubsub#33]
Do you have a JavaScript client that can connect to an instance of this running on the server?

**Comment by xmuskrat** [comment]
Found https://github.com/permitio/fastapi_websocket_pubsub/discussions/18

**Comment by orweis** [comment]
> Found #18

As I noted in #18 - If you want to pickup that challenge we'd be happy to provide guidance.
