### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by arkadybag** [permitio/fastapi_websocket_pubsub#43]
https://github.com/permitio/fastapi_websocket_pubsub/blob/90304e3b68eb970f9d56057ea0613028cf748de5/README.md?plain=1#L110

Instead of `on_event` it should be `on_trigger`, am I right?

**Comment by orweis** [comment]
You are correct ;-) - good catch.
Would you like to submit a PR - so you can get the contribution credit on Github ?
