### ISSUE TITLE
Support for websockets>=11?

### ISSUE THREAD

**Issue by Graeme22** [permitio/fastapi_websocket_pubsub#71]
Hello! Thanks for this great library.

I'm currently trying to use in an application, but another library I'm using requires websockets>=11. I noticed this library requires an older version. Is there a particular reason for this, or do the dependencies just need to be updated?

Thanks!

**Comment by orweis** [comment]
Hi, 🤗,
I'm pretty sure it's just version pining as it was not tested. You can open a PR with updating to the new version, and run the tests.

**Comment by Graeme22** [comment]
Well, I can't get the tests to pass locally, but looking at the open PRs it seems like none of them are passing the tests currently

**Comment by Graeme22** [comment]
Should I do a PR anyways? Looks like `fastapi-websocket-rpc` has the same dependency issues.

**Comment by orweis** [comment]
Oh seems @roekatz broke this on one of recent releases. We'd love need to fix that first.

**Comment by orweis** [comment]
> Should I do a PR anyways? Looks like `fastapi-websocket-rpc` has the same dependency issues.

Spoke to @roekatz he'll fix the tests,
In the meantime you can do the PR and test against the version from the previous month where tests still pass, and then we'd merge all these.

**Comment by roekatz** [comment]
> > Should I do a PR anyways? Looks like `fastapi-websocket-rpc` has the same dependency issues.
> 
> Spoke to @roekatz he'll fix the tests, In the meantime you can do the PR and test against the version from the previous month where tests still pass, and then we'd merge all these.

I took a short look. The tests fail even when I run them with the supposedly good older version (I suspect it has to do with a newer version of one of the libraries) - so testing against the older version might not help.

I'll fix those tests ASAP (sorry for not doing it so far) - But I still suggest not holding back with the PR (assuming those are the same tests that fail with the same errors). I'll make sure everything passes before releasing a new version.

**Comment by ff137** [comment]
Good day! I'm just wondering - when we can expect a new release that includes this websocket version bump?

**Comment by orweis** [comment]
@roekatz can you take care of this when you're back tomorrow?

**Comment by ff137** [comment]
Please 🙏 :-)

**Comment by roekatz** [comment]
Hi @ff137 - Version 0.3.9 that was released to pypi last month should already include this fix :)
(We'll make sure we also create Releases here to reflect the pypi publishes)

**Comment by ff137** [comment]
@roekatz ah, thank you for confirming! I was indeed going off the GitHub releases, and missed that our poetry.lock file already includes the latest _pubsub release.

I see now it is the fastapi_websocket_rpc release that is the one rolling back to the older web socket version. Since _pubsub depends on _rpc

**Comment by roekatz** [comment]
@ff137 let me check fastapi_websocket_rpc then. I'll release a new version there as well if needed

**Comment by roekatz** [comment]
@ff137 Released `fastapi_websocket_rpc==0.1.26`
Lmk if this is now solved

**Comment by ff137** [comment]
Brilliant! That resolves it 👏 thank you! @roekatz
