### ISSUE TITLE
Channel Closed before RPC response for 5b0a37a08a51 could be received

### ISSUE THREAD

**Issue by cooper87** [permitio/fastapi_websocket_pubsub#74]
1. I send some log data to client(web)
2. Then I switch tabs (two tab in one page)
3. server throws exception like below:

fastapi_websocket_rpc.rpc_channel.RpcChannelClosedException: Channel Closed before RPC response for 4af54b2301024c419c30
5b0a37a08a51 could be received
Failed to notify subscriber sub_id=1c16a0c075014bb7a9f00022bde7c831 with topic=test_path_2#log_data
Traceback (most recent call last):
  File "Z:\datasmart\datasmart\venv\Lib\site-packages\fastapi_websocket_pubsub\event_notifier.py", line 222, in
callback_subscribers
    await self.trigger_callback(data, topic, subscriber_id, event)
  File "Z:\datasmart\datasmart\venv\Lib\site-packages\fastapi_websocket_pubsub\event_notifier.py", line 180, in
trigger_callback
    await subscription.callback(subscription, data)
  File "Z:\datasmart\datasmart_backend\venv\Lib\site-packages\fastapi_websocket_pubsub\rpc_event_methods.py", line 26, i
n callback
    await self.channel.other.notify(subscription=sub, data=data)
  File "Z:\datasmart\datasmart\venv\Lib\site-packages\fastapi_websocket_rpc\rpc_channel.py", line 397, in call
    return await self.wait_for_response(promise, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\datasmart\datasmart\venv\Lib\site-packages\fastapi_websocket_rpc\rpc_channel.py", line 370, in wait_f
or_response
    raise RpcChannelClosedException(
fastapi_websocket_rpc.rpc_channel.RpcChannelClosedException: Channel Closed before RPC response for fd885a529545428594b6
c10ecb695e78 could be received

someone cloud help me?  thanks very much.

**Comment by orweis** [comment]
Which client are you using on the browser? 
There is no official JS client

https://github.com/permitio/fastapi_websocket_pubsub/discussions/42

**Comment by cooper87** [comment]
**using react in client.**

client code below:
```
import emitter from "@/lib/mitt";

  const getLog = (data) => {
    const { page_id, log } = data;

    setLogs((pre) => {
      return { ...pre, [page_id]: [...pre[page_id], log] };
    });
  };

  useEffect(() => {
    if (socket) {
      emitter.on(`${projectName}#log_data`, getLog);
      // subscribe message
      socket.sub([`${projectName}#log_data`]);
      return () => {
        emitter.off(`${projectName}#log_data`, getLog);
      };
    }
  }, [socket]);
```

**Comment by orweis** [comment]
I mean which RPC client implementation did you use?

I'm guessing you are just using a naked websocket here... That won't work.
Check out the other thread I shared for more details.
